package Acme::CPANModulesBundle::Import::PerlAdvent::2017;

# DATE
# VERSION

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in
L<http://perladvent.org/2017/>. Visit the URL for the full contents.
