package Acme::CPANModules::Import::PerlAdvent::2017_12_22;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/2017-12-22.html] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"SQL::Abstract"}],summary=>"Modules mentioned in Perl Advent Calendar 2017 (day 22)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017 (day 22)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/2017-12-22.html> (retrieved on 2018-02-18). Visit the URL for the full contents.

