package Acme::CPANModules::Import::PerlAdvent::2017;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"App::GHPT::Wrapper::Ourperl"},{module=>"Term::Choose"},{module=>"Eval::Closure"},{module=>"Acme::Damn"},{module=>"CPAN::Meta::Requirements"},{module=>"Perl::PrereqScanner"},{module=>"Perl::PrereqScanner::Lite"},{module=>"Perl::PrereqScanner::NotQuiteLite"},{module=>"Mojo::Collection"},{module=>"Mojo::DOM"},{module=>"Mojo::Message::Response"},{module=>"ojo"},{module=>"Moo"},{module=>"MooseX::AttributeShortcuts"},{module=>"MooseX::StrictConstructor"},{module=>"Moose::Meta::Attribute::Native::Trait::Counter"},{module=>"MooseX::ClassAttribute"},{module=>"MooseX::LazyRequire"},{module=>"MooseX::UndefTolerant::Attribute"},{module=>"Reindeer"},{module=>"Try::Tiny"},{module=>"namespace::autoclean"},{module=>"SQL::Abstract"},{module=>"Params::Validate"},{module=>"Params::ValidationCompiler"},{module=>"WWW::YouTube::Download"},{module=>"Unicode::UCD"},{module=>"Path::Tiny"},{module=>"Test::Perl::Critic"},{module=>"Perl::Critic"},{module=>"Devel::MAT"},{module=>"utf8"},{module=>"Emoji::NationalFlag"},{module=>"DBIx::Class"}],summary=>"Modules mentioned in Perl Advent Calendar 2017"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/> (retrieved on 2018-02-18). Visit the URL for the full contents.

