package Acme::CPANModules::Import::PerlAdvent::2017_12_23;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/2017-12-23.html] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"Eval::Closure"},{module=>"Params::Validate"},{module=>"Params::ValidationCompiler"}],summary=>"Modules mentioned in Perl Advent Calendar 2017 (day 23)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/2017-12-23.html> (retrieved on 2018-02-18). Visit the URL for the full contents.

