package Acme::CPANModules::Import::PerlAdvent::2017_12_02;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/2017-12-02.html] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"Emoji::NationalFlag"}],summary=>"Modules mentioned in Perl Advent Calendar 2017 (day 02)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017 (day 02)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/2017-12-02.html> (retrieved on 2018-02-18). Visit the URL for the full contents.

