package Acme::CPANModules::Import::PerlAdvent::2017_12_24;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/2017-12-24.html] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"WWW::YouTube::Download"}],summary=>"Modules mentioned in Perl Advent Calendar 2017 (day 24)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/2017-12-24.html> (retrieved on 2018-02-18). Visit the URL for the full contents.

