package Acme::CPANModules::Import::PerlAdvent::2017_12_14;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2017/2017-12-14.html] (retrieved on 2018-02-18). Visit the URL for the full contents.",entries=>[{module=>"Acme::Damn"},{module=>"CPAN::Meta::Requirements"},{module=>"Perl::PrereqScanner"},{module=>"Perl::PrereqScanner::Lite"},{module=>"Perl::PrereqScanner::NotQuiteLite"}],summary=>"Modules mentioned in Perl Advent Calendar 2017 (day 14)"};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2017 (day 14)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2017/2017-12-14.html> (retrieved on 2018-02-18). Visit the URL for the full contents.

